config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "articles#index"

  resources :topics do
    resources :articles do
      resources :comments, only: [:create, :destroy]
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :comments, dependent: :destroy

  default_scope { order('created_at DESC') }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user

  validates :body, length: { minimum: 5, maximum: 1000 }, presence: true
  validates :user, presence: true
  default_scope { order('created_at DESC') }
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :articles
  default_scope { order('created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]

  def index
    @articles = Article.all
    @topics = Topic.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @article = Article.new
  end

  def create
    @article = Article.new
    @article.title = params[:article][:title]
    @article.body = params[:article][:body]
    @article.topic_id = params[:topic_id]
    @article.user = current_user

    if @article.save
      flash[:notice] = "Your article was saved successfully."
      redirect_to topic_article_path(@article.topic, @article)

    else
      flash[:alert] = "Your article wasn't saved. Please try again."
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.title = params[:article][:title]
    @article.body = params[:article][:body]

    if @article.save
      flash[:notice] = "Your article was updated successfully."
      redirect_to topic_article_path(@article.topic, @article)

    else
      flash[:alert] = "Your article wasn't updated. Please try again."
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])

    if @article.destroy
      flash[:notice] = "Your article was deleted successfully."
      redirect_to root_path

    else
      flash[:alert] = "Your article wasn't deleted. Please try again."
      render :show
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :user_signed_in?
  before_action :authorize_user, only: [:destroy]

  def create
    @article = Article.find(params[:article_id])
    comment = @article.comments.new(comment_params)
    comment.user = current_user

    if comment.save
      flash[:notice] = "Comment saved successfully."
      redirect_to topic_article_path(@article.topic, @article)
    else
      flash[:alert] = "Comment failed to save. Please try again."
      redirect_to topic_article_path(@article.topic, @article)
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    comment = @article.comments.find(params[:id])

    if comment.destroy
      flash[:notice] = "Comment was deleted successfully."
      redirect_to topic_article_path(@article.topic, @article)
    else
      flash[:alert] = "Comment wasn't deleted. Please try again."
      redirec_to topic_article_path(@article.topic, @article)
    end
  end


  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def authorize_user
    @article = Article.find(params[:article_id])
    comment = Comment.find(params[:id])
    unless current_user == comment.user #|| current_user.admin?
      flash[:alert] = "You do not have permission to delete this comment."
      redirect_to topic_article_path(article.topic, article)
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new
    @topic.name = params[:topic][:name]
    @topic.description = params[:topic][:description]

    if @topic.save
      flash[:notice] = "Topic was saved successfully."
      redirect_to @topic
    else
      flash.now[:alert] = "Error creating the topic. Please try again."
      redirect_to new_topic
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.name = params[:topic][:name]
    @topic.description = params[:topic][:description]

    if @topic.save
      flash[:notice] = "Topic was saved successfully."
      redirect_to @topic
    else
      flash.now[:alert] = "Error creating the topic. Please try again."
      redirect_to edit_topic
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
       flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
       redirect_to root_path
     else
       flash.now[:alert] = "There was an error deleting the topic."
       render :show
     end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def user_is_authorized_for_comment?(comment)
   current_user #&& (current_user == comment.user || current_user.admin?)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<h1>New Article</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for articles</p>
    <ul>
      <li>Make sure it is unique and can't be found anywhere else.</li>
      <li>Make sure you won't add any external links or product promotion.</li>
      <li>Make sure your article is focused in delivering value about the chosen topic.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for [@article.topic, @article] do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter article title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter article body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/index.html.erb
<h1>Most recent Articles<h1>
<% @articles.limit(10).each do |article| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to article.title, topic_article_path(article.topic, article) %> <small>(<%= link_to article.topic.name, topic_path(article.topic) %>)</small>
      </h4>
    </div>
  </div>
<% end %>

<h2>Want to add an article?</h2>
<p>
  <strong>Choose a topic to add it to:</strong>
  <ul>
    <% @topics.each do |topic| %>
      <li><%= link_to topic.name, topic %> --> <%= topic.articles.count %> article(s)</li>
    <% end %>
  </ul>
  <strong>Or <%= link_to 'create a new topic', new_topic_path %></strong>
</p>

app/views/articles/new.html.erb
<h1>New Article</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for articles</p>
    <ul>
      <li>Make sure it is unique and can't be found anywhere else.</li>
      <li>Make sure you won't add any external links or product promotion.</li>
      <li>Make sure your article is focused in delivering value about the chosen topic.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for [@topic, @article] do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter article title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter article body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= @article.body %></p>
    <div>
      <h3>Comments</h3>
      <%= render @article.comments %>
    </div>
    <% if current_user %>
      <%= render 'comments/form', comment: Comment.new, article: @article %>
    <% end %>
  </div>
    <div class="col-md-4">
      <% if current_user && current_user == @article.user %>
        <%= link_to "Edit", edit_topic_article_path(@article.topic, @article), class: 'btn btn-success' %>
        <%= link_to "Delete", topic_article_path(@article.topic, @article), method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this article?'} %>
      <% end %>
      <%= link_to "Current Topic", topic_path(@article.topic), class: 'btn btn-success' %>
    </div>
</div>

app/views/comments/_comment.html.erb
<div class="media">
  <div class="media-body">
    <small>
      <%= comment.user.email %> commented <%= time_ago_in_words(comment.created_at) %> ago
      <% if user_is_authorized_for_comment?(comment) %>
        <%= link_to "Delete", topic_article_comment_path(@article.topic, @article, comment), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' } %>
      <% end %>
    </small>
    <p><%= comment.body %></p>
  </div>
</div>

app/views/comments/_form.html.erb
<h4>Add a comment</h4>

<%= form_for [article.topic, article, comment] do |f| %>
  <div class="form-group">
    <%= f.label :body, class: 'sr-only' %>
    <%= f.text_field :body, class: 'form-control', placeholder: "Enter a new comment" %>
  </div>
  <%= f.submit "Submit Comment", class: 'btn btn-default pull-right' %>
<% end %>

app/views/comments/create.js.erb
<% if @comment.valid? %>
  $('.js-comments').prepend("<%= escape_javascript(render(@comment)) %>");
  $('.new-comment').html("<%= escape_javascript(render partial: 'comments/form', locals: { article: @article, comment: @new_comment }) %>");
<% else %>
  $('.new-comment').html("<%= escape_javascript(render partial: 'comments/form', locals: { article: @article, comment: @comment }) %>");
<% end %>

app/views/comments/destroy.js.erb
<% if @comment.destroyed? %>
  $('#comment-<%= @comment.id %>').hide();
<% else %>
  $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Articles</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <% if user_signed_in? %>
        <li>Logged in as <strong><%= current_user.email %></strong></li>
        <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
        <li><%= link_to "Articles", root_path, :class => 'navbar-link' %></li>
      <% else %>
        <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
        <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
        <li><%= link_to "Articles", root_path, :class => 'navbar-link' %></li>
      <% end %>
    </ul>
  </div>

  <div class="flash">
    <% if flash[:notice] %>
      <div class='alert alert-success'>
        <button type='button' class='close' data-dismiss='alert'>&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class='alert alert-danger'>
        <button type='button' class='close' data-dismiss='alert'>&times;</button>
        <%= flash[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class='alert alert-warning'>
        <button type='button' class='close' data-dismiss='alert'>&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/topics/edit.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure it doesn't exist already.</li>
      <li>Make sure it doesn't fit in any of the existing topics.</li>
      <li>Make sure we have enough content to populate it.</li>
      <li>Use the topic description to define the scope for each topic.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
  <div class="col-md-8">
    <% @topics.each do |topic| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to topic.name, topic %>
          </h4>
          <small>
            <%= topic.description %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure it doesn't exist already.</li>
      <li>Make sure it doesn't fit in any of the existing topics.</li>
      <li>Make sure we have enough content to populate it.</li>
      <li>Use the topic description to define the scope for each topic.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<% if current_user %>
  <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
<% end %>

<div class="row">
  <div class="col-md-8">
    <p class="lead"><%= @topic.description %></p>
    <% @topic.articles.each do |article| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to article.title, topic_article_path(@topic, article) %>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
    <div class="col-md-4">
      <% if current_user %>
        <%= link_to "New Article", new_topic_article_path(@topic), class: 'btn btn-success' %>
        <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
      <% end %>
    </div>
</div>

app/views/users/index.html.erb
<h1>Welcome to Articles<h1>